/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package soundrecorder;

import javax.sound.sampled.LineUnavailableException;

public class App {

    public static void main(String[] args) {
        System.out.println("Welcome to Sound Recorder!");
    }
}
